### ISSUE TITLE
register more app templates

### ISSUE THREAD

**Issue by Andrwe** [owncloud/templateeditor#12]
Hi,

currently I'm writing an app which uses e-mail templates.

I like the idea of manipulating these templates via admin settings.
Unfortunately the editable templates are hardcoded in templateeditor.
It would be nice if you can implement a method to allow other apps registering their templates as editable thus providing a general method of editing the templates.

My first idea for implementing the registration is to implement a global public method which addes the path and display string to the database.
Then exténd the method getEditableTemplates() to get them from the database.

What do you think about this feature?
Would it be possible to implement it?
Is there a better way of implementation?

Kind regards,
Andrwe

**Comment by butonic** [comment]
https://github.com/owncloud/core/pull/12613 has been closed. the way forward is the symphony eventhandler.
