### ISSUE TITLE
Add possibility to edit non english templates on web UI

### ISSUE THREAD

**Issue by rakekniven** [owncloud/templateeditor#19]
### Expected behaviour
I want to edit german mail templates inside web UI as well

### Actual behaviour
Only english templates can be edited on web UI

### Server configuration
**Operating system**: Linux embedded
**Web server:** Apache 2.4.7
**Database:** MySQL
**PHP version:** 5.5.21
**ownCloud version:** 8.0.0
**Updated from an older ownCloud or fresh install:** fresh

### Client configuration
**Browser:** Firefox 36.0
**Operating system:** OS X

**Comment by karlitschek** [comment]
@butonic Any idea?

**Comment by DeepDiver1975** [comment]
The editor does not respect languages afaik

**Comment by butonic** [comment]
The template editor allows you to edit the template files. If you use `$l->t("The share will expire on %s.", array($_['expiration']))` the translations will be taken from the l10n folder. So whatever string you put in there needs a matching translation in the l10n folder. We could allow altering the translations ... @jancborchardt should probably create a mockup before we dive into coding.

**Comment by fux84** [comment]
from which l1on folder is it taken? Sorry for my question, but i dont get it...
