### ISSUE TITLE
theme "default" hardcoded

### ISSUE THREAD

**Issue by felixboehm** [owncloud/templateeditor#24]
https://github.com/owncloud/templateeditor/blob/master/lib/mailtemplate.php#L127

default theme should not be displayed in admin settings if another theme is configured and the default theme is removed from themes folder. 

I suggest to have the current configured theme as first entry in theme dropdown list.

**Comment by karlitschek** [comment]
@butonic What do you think?

**Comment by butonic** [comment]
Yes, makes sense.
