### ISSUE TITLE
Error trying to switch mail template themes

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/templateeditor#28]
### Steps to reproduce

1. Install 8.1 
2. Navigate to the admin page
3. Click on Mail Templates hot link
4. Change theme from default to example

### Expected behaviour

Should see the example templates

### Actual behaviour

Get an error:

I verified that the themes/example directory has the same permissions as the themes/default directory.

![p342](https://cloud.githubusercontent.com/assets/8480343/7595350/72dda512-f8b4-11e4-9ba1-0ee7ce316879.PNG)

I also tried to create a new theme by copying over default to jrm-default and adding it to config.php.

I get the same error when trying to switch to it on the admin page.

### Server Host info:

Ubuntu 14.04
PHP 5.5.9

### Server configuration:

ownCloud Enterprise Edition 8.1 beta 1 (daily) Build:2015-05-12T03:08:46+00:00 20d2d8d3ddee2750343bdec69a3e7031b710039a

**Comment by DeepDiver1975** [comment]
duplicate

**Comment by DeepDiver1975** [comment]
> duplicate

https://github.com/owncloud/templateeditor/issues/21

**Comment by DeepDiver1975** [comment]
fix is here - https://github.com/owncloud/templateeditor/pull/27 - please test - thx
