### ISSUE TITLE
Template does not reset

### ISSUE THREAD

**Issue by PVince81** [owncloud/templateeditor#32]
### Steps

1) Modify an email template (sharing email(http)) in this instance
2) Press SAVE
3) Press RESET
4) Refresh the page, select it again

### Expected

Template is reset

### Actual

The message "Reset" is shown in green but the template is still the original one.

**Comment by DeepDiver1975** [comment]
lets see if we can fix that for 8.2

**Comment by PVince81** [comment]
>lets see if we can fix that for 8.2

Really ? This is non-critical to put in a RC2 ...

**Comment by PVince81** [comment]
and also very old

**Comment by PVince81** [comment]
This was the original ticket: https://github.com/owncloud/core/issues/10906
