### ISSUE TITLE
Lost password email has wrong path in MailTemplate::getEditableTemplates() (oC 9)

### ISSUE THREAD

**Issue by mfleonhardt** [owncloud/templateeditor#41]
Path to lost password email is now core/templates/lostpassword/email.php:

See: https://github.com/owncloud/core/commit/d6a63016ae0e14efeefd763a1042c515b60b3f7d#diff-99e3dc575aa9a63551d7cb48beb8d843

**Comment by Tealk144** [comment]
I have the same error

Server configuration
**Operating system:** Debian 8.0 jessie minimal
**Web server:** Apache/2.4.10 (Debian)
**Database:** mysqlnd 5.0.11
**PHP version:** 5.6.17-0+deb8u1
**ownCloud version (see ownCloud admin page):** 9.0.0 (stable)
**Updated from an older ownCloud or fresh install:** No
**ownCloud log (data/owncloud.log):** nothing
![a0pwo4z_700b_v1](https://cloud.githubusercontent.com/assets/12276250/14385360/4fee1ffe-fda0-11e5-85f9-984b7a5f857e.jpg)
**Special configuration** (external storage, external authentication, reverse proxy, server-side-encryption): server-side-encryption

**Comment by strowi** [comment]
Hi,

im  seeing the same error on a 9.0.1-installation.

**Comment by chriseqipe** [comment]
Just made a patch.

**Comment by chriseqipe** [comment]
Just made a patch. See https://github.com/owncloud/templateeditor/pull/42/commits/b0da006281b0fb0dac8a32b9e977cf6181679bc4
