### ISSUE TITLE
Publish in market

### ISSUE THREAD

**Issue by PVince81** [owncloud/templateeditor#53]
- [ ] unbundle in 10.0.0 (@pvince81 adjust build script)
- [ ] publish to market

**Comment by PVince81** [comment]
Since the app is broken I suggest to first unbundle it but not publish to market until it's fixed.

@phisch

**Comment by phisch** [comment]
It should work just fine in my PR's. But this includes some new features, which we will probably publish with 10.0.1? @PVince81 

Getting it into market is good either way.

**Comment by DeepDiver1975** [comment]
> But this includes some new features, which we will probably publish with 10.0.1? @PVince81

you can set the minimum requirement in info.xml to 10.0.1 - this should work out fine then ....

**Comment by VicDeo** [comment]
@patrickjahns @owncloud/qa Could we start with release preparations here?

**Comment by patrickjahns** [comment]
Sure thing - anything besides https://github.com/owncloud/templateeditor/pull/52 that was changed and need to be moved to QA milestone?

**Comment by VicDeo** [comment]
@patrickjahns https://github.com/owncloud/templateeditor/pull/52 only
