### ISSUE TITLE
Can not edit mail templates when no theme is selected

### ISSUE THREAD

**Issue by patrickjahns** [owncloud/templateeditor#58]
## Steps to reproduce

Install templateeditor from  https://github.com/owncloud/templateeditor/tree/release/0.2.0
Do not have a custom template enabled
Edit one of the templates and try to save

## Expected Behavior
I can edit/save the (default) template

## Actual Behavior
... empty text field in which I can write text - but saving is stuck
![image](https://user-images.githubusercontent.com/6403243/33549087-a8498e24-d8e9-11e7-827b-c0f75de6e5c9.png)

OC exception:
```
{
"reqId":"cpjG1XrmvLlxJ58JnJYR",
"level":3,
"time":"2017-12-04T10:52:32+00:00",
"remoteAddr":"172.17.0.1",
"user":"admin"
,"app":"index",
"method":"POST",
"url":"/owncloud/index.php/apps/templateeditor/settings/mailtemplate",
"message":"Exception: {
"Exception":"TypeError","Message":"Argument 1 passed to OCA\TemplateEditor\MailTemplate::__construct() must implement interface OCP\Theme\ITheme, boolean given, called in /var/www/owncloud/apps/templateeditor/lib/TemplateEditor.php on line 90","Code":0,"Trace":"nn
#0 /var/www/owncloud/apps/templateeditor/lib/TemplateEditor.php(90): OCA\TemplateEditor\MailTemplate->__construct(false, 'core/templates/...')
n#1 /var/www/owncloud/apps/templateeditor/lib/Controller/AdminSettingsController.php(72): OCA\TemplateEditor\TemplateEditor->getMailTemplate('', 'core/templates/...')
n#2 [internal function]: OCA\TemplateEditor\Controller\AdminSettingsController->updateTemplate('', 'core/templates/...', 'asdfsaf')
n#3 /var/www/owncloud/lib/private/AppFramework/Http/Dispatcher.php(159): call_user_func_array(Array, Array)
n#4 /var/www/owncloud/lib/private/AppFramework/Http/Dispatcher.php(89): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\TemplateEditor\Controller\AdminSettingsController), 'updateTemplate')
n#5 /var/www/owncloud/lib/private/AppFramework/App.php(98): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\TemplateEditor\Controller\AdminSettingsController), 'updateTemplate')
n#6 /var/www/owncloud/lib/private/AppFramework/Routing/RouteActionHandler.php(46): OC\AppFramework\App::main('OCA\TemplateEdi...', 'updateTemplate', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
n#7 [internal function]: OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
n#8 /var/www/owncloud/lib/private/Route/Router.php(307): call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
n#9 /var/www/owncloud/lib/base.php(928): OC\Route\Router->match('/apps/templatee...')
n#10 /var/www/owncloud/index.php(56): OC::handleRequest()
n#11 {main}","File":"/var/www/owncloud/apps/templateeditor/lib/MailTemplate.php","Line":38}"
}

```

**Comment by patrickjahns** [comment]
@VicDeo 
I don't know if the expected behavior is the correct behavior - maybe we need to "disable" the editing functionality if there is no custom theme selected/present?

**Comment by PVince81** [comment]
yes, disable

bonus point if you can detect non-writeable theme folders when theme app is there and show an appropriate message

**Comment by VicDeo** [comment]
@PVince81 I think it would be better:
![no-themes](https://user-images.githubusercontent.com/991300/34172216-612aa094-e502-11e7-9972-b09879187ce4.png)

**Comment by VicDeo** [comment]
or even better wording: `You need own theme to edit  mail templates. How to [create a theme](https://doc.owncloud.org/server/10.0/developer_manual/core/theming.html)`

**Comment by PVince81** [comment]
@VicDeo great ideas!

**Comment by SergioBertolinSG** [comment]
@pmaier1 There was this ticket already created about this topic.

Without a theme enabled this app cannot work. My question is why the default community look and feel is not considered a theme?

**Comment by SergioBertolinSG** [comment]
@VicDeo It is possible to make this app work without enabling an extra theme?

@PVince81  Maybe the solution could be to make the community edition to have a theme enabled with its look and feel? Not sure if that would be useful in other parts.

**Comment by pmaier1** [comment]
Hmm, this is not really user-friendly. I see the point that altering the templates should not alter the default theme to be able to restore the defaults easily. Still, the admin would need to add a theme or create a basic theme himself in order to be able to change the mail templates? If this is the case, that's not very helpful. 
Maybe the templateeditor could carry a copy of the basic theme to be able to customize that while still being able to restore defaults. Or other ideas?

**Comment by VicDeo** [comment]
@SergioBertolinSG 
`default community look and feel` are core templates. 
And it's not advised change core files.

**Comment by patrickjahns** [comment]
@pmaier1 
Creating a theme is straight forward now - we even have a simple script that gives you a starting point.

Doing "magic" to also make things happen on the default theme should be out of scope for the current release

**Comment by pmaier1** [comment]
Ok, after discussing with @patrickjahns this is what we have:
- The issue in here is not a blocker for unbundling as there's more flexibility for upgrading when the templateeditor is unbundled

- Current behavior is not acceptable for several reasons
  - When standard oC theme is in use the admin can't customize mail templates without further action
  - UI customizations from ownBrander don't produce theme apps yet => same issue as with standard oC theme

So with the current approach an admin can only use theme-enterprise (EE only; unbranded) or create their own theme to be able to customize mail templates.

Therefore it either needs to be possible to customize mail templates from standard theme or standard theme and ownBrander outputs become theme apps as well.

**Comment by VicDeo** [comment]
>ownBrander don't produce theme apps yet 

NP, legacy themes are still supported

> can only use theme-enterprise (EE only; unbranded) 

not exactly, what about theme-example?

**Comment by pmaier1** [comment]
> not exactly, what about theme-example?

You don't want to switch to theme-example which comes with totally different design if you want to customize mail templates.

> NP, legacy themes are still supported

I can't edit the mail templates with standard theme in 10.0.7. Same should be the case with an ownBrander-customized theme as it just alters standard theme, right?

![templates](https://user-images.githubusercontent.com/21193500/36854666-d4a42796-1d71-11e8-8145-355d8800b502.png)

**Comment by VicDeo** [comment]
>Same should be the case with an ownBrander-customized theme as it just alters standard theme, right?

nope. I don't familiar with ownbrander but suspect it to produce a legacy theme that needs to put in 'themes' directory under OC webroot
Such themes are still supported by templateeditor as I wrote above

**Comment by pmaier1** [comment]
@michaelstingl Can you clarify, please? ^

Still you can't edit mail templates if you don't have a custom theme.

**Comment by michaelstingl** [comment]
> Still you can't edit mail templates if you don't have a custom theme.

yes, this is correct. mail templates are files that gets copied to your theme or theme-app when modified.

**Comment by michaelstingl** [comment]
> Creating a theme is straight forward now

@patrickjahns docs? link?

**Comment by VicDeo** [comment]
@michaelstingl https://github.com/owncloud/templateeditor/issues/58#issuecomment-369638151
*create a theme* is a link to docs

**Comment by patrickjahns** [comment]
@michaelstingl 
To me the Documentation page is quite extensive - and has easy steps to get started.

https://doc.owncloud.org/server/latest/developer_manual/core/theming.html#how-to-create-a-new-theme

**Comment by PVince81** [comment]
is the doc above enough to reduce this to p3 or close ?

**Comment by felixboehm** [comment]
@patrickjahns @VicDeo reducing prio here.
Please let me know if you still need a high prio here.

**Comment by PVince81** [comment]
to be rescheduled if relevant -> backlog
