### ISSUE TITLE
Scope of the dropdown for template editor

### ISSUE THREAD

**Issue by davitol** [owncloud/templateeditor#61]
Why do we have a dropdown for the theme, when themes not enabled are not listed in that dropdown, and we cannot enable two themes at the same time.?

![screen shot 2018-01-12 at 12 28 28](https://user-images.githubusercontent.com/10596560/34873733-92308392-f796-11e7-9ab4-b18c91f3646f.png)

![screen shot 2018-01-12 at 12 49 27](https://user-images.githubusercontent.com/10596560/34873883-10e6662a-f797-11e7-951b-2606107d05a9.png)

**Comment by pmaier1** [comment]
Well, in that case this does not make sense, agree. So easiest solution would be to enable choosing and editing of disabled themes via the dropdown if this is possible? @VicDeo

**Comment by PVince81** [comment]
moving to triage until we decide this is in scope for assignment
