### ISSUE TITLE
Mail templates autodetection

### ISSUE THREAD

**Issue by VicDeo** [owncloud/templateeditor#74]
it is possible to locate available mail templates automatically e.g. by location `templates/mail` 
It's a matter of design how to pass  the following metadata to the templateeditor:
- usage of the template
- type of the template (html/plain)
- priority/sort order ?

In future it will allow easily extend the app to edit any kind of template and not only mail templates  just by changing `templates/mail` to `templates`  and adding appropriate metadata where needed. /considering templates with no metadata as non-editable/

**Comment by VicDeo** [comment]
@PVince81

**Comment by PVince81** [comment]
Sounds like a good plan. It would likely require scanning the templates folders of every app.

any objections @DeepDiver1975 @tomneedham ?

**Comment by PVince81** [comment]
In the future we'd like to move the templates to the database, like PHPBB does (according to @VicDeo):
- template files still stored on disk
- modified templates are stored in DB or other location
=> raised here https://github.com/owncloud/templateeditor/issues/75

This tells me that it doesn't make sense to store the template metadata directly in the template (as comments / special annotations), and it makes more sense to put this inside of info.xml.

This means that any editable template needs to be exposed by apps through info.xml.

We could then in a first step edit all apps that have the known templates from the current hard-coded list and move these to info.xml.

This means that whenever the template editor settings panel is open, we'd scan info.xml from all enabled apps.

**Comment by PVince81** [comment]
I'm setting this to "maybe some day" now as we need to discuss the concept.
I'm not sure if moving forward with this right now is the right move.
This might perhaps be better combined with https://github.com/owncloud/templateeditor/issues/75.
In any case, if modifying info.xml of any apps will trigger a re-release of said apps.
